version: "3.3"
services:
  server:
    hostname: auth-server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - ./server:/go/src/server
    ports:
      - 4000:4000
    environment:
      - PRIVATE_KEY=$PRIVATE_KEY
      - MONGODB_HOST=$MONGODB_HOST
      - MONGODB_USERNAME=$MONGODB_USERNAME
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_DATABASE=$MONGODB_DATABASE
      - MONGODB_PORT=$MONGODB_PORT
    depends_on:
      - database
    networks:
      - hellosign
  app:
    hostname: hellosign-app
    build:
      context: ./app
      dockerfile: ./Dockerfile
    volumes:
      - /usr/src/app/node_modules
      - ./app:/usr/src/app
      - /usr/src/app/.next
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    depends_on:
      - server
      - database
    networks:
      - hellosign
  database:
    hostname: hellosign-db
    image: mongo
    volumes:
      - database:/data/db
    ports:
      - 27017-27019:27017-27019
    environment:
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    networks:
      - hellosign
  nginx:
    build:
      context: ./infra
      dockerfile: ./Dockerfile.nginx
    ports:
      - 80:80
    networks:
      - hellosign
volumes:
  database:
    driver: local
networks:
  hellosign:
    driver: bridge
