services:
  app:
    domainname: hellosign.local
    build:
      dockerfile: './Dockerfile'
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - MONGODB_HOST=$MONGODB_HOST
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_DATABASE=$MONGODB_DATABASE
      - MONGODB_PORT=$MONGODB_PORT
    depends_on:
      - database
    networks:
      - hellosign
  database:
    domainname: hellosign-db.local
    image: mongo
    volumes:
      - ./database:/data/db
    ports:
      - 27017-27019:27017-27019
    environment:
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    networks:
      - hellosign
volumes:
  database:
    driver: local
networks:
  hellosign:
    driver: bridge
